version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin:ro
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: fenglc/pgadmin4
#    volumes:
#       - ./pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"

#  Gerek Yok  links:
#  Gerek Yok    - postgres:postgres
    restart: always
